version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - database:/app/database  # ใช้ volume เดียวกันสำหรับ database
    environment:
      - FLASK_ENV=development
    depends_on:
      - database
    networks:
      - ai

  frontend:
    build: ./my-app
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app
      - database:/app/database  # ใช้ volume เดียวกันสำหรับ database
    depends_on:
      - backend
      - database
    networks:
      - ai

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=postgre
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    networks:
      - ai
    volumes:
      - database:/var/lib/postgresql/data  # ใช้ volume เดียวกันสำหรับข้อมูล database

networks:
  ai:
    driver: bridge
    attachable: false
    external: false

volumes:
  database:
    driver: local
    external: false
